# Generated by Django 3.1.5 on 2021-01-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0003_auto_20210128_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.TextField(default='Good Day!'),
        ),
    ]
