# Generated by Django 3.1.5 on 2021-01-29 05:01

import datetime
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0004_memory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
