# Generated by Django 3.1.5 on 2021-01-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0005_auto_20210129_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
